"""procedural

Revision ID: 00bc34b2cc6b
Revises: ce3ec0f1fca1
Create Date: 2019-12-11 21:20:42.546657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00bc34b2cc6b'
down_revision = 'ce3ec0f1fca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription', 'frequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription', sa.Column('frequency', mysql.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
