"""top

Revision ID: 08286575be7f
Revises: 59b86c7636d7
Create Date: 2019-12-05 17:39:06.303960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08286575be7f'
down_revision = '59b86c7636d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_posts',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rank')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_posts')
    # ### end Alembic commands ###
