"""muuu

Revision ID: 235f62ab03a4
Revises: fdf1a577140f
Create Date: 2019-12-06 19:27:08.458026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '235f62ab03a4'
down_revision = 'fdf1a577140f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('top_posts_ibfk_3', 'top_posts', type_='foreignkey')
    op.drop_column('top_posts', 'subscribers')
    op.drop_column('top_posts', 'hospital_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_posts', sa.Column('hospital_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('top_posts', sa.Column('subscribers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('top_posts_ibfk_3', 'top_posts', 'hospital', ['hospital_id'], ['unique_id'])
    op.drop_column('prescription', 'active')
    # ### end Alembic commands ###
