"""top

Revision ID: 332d13c99688
Revises: 37a39d65afd5
Create Date: 2019-12-05 17:28:40.328261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332d13c99688'
down_revision = '37a39d65afd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_forums',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.forum_id'], ),
    sa.PrimaryKeyConstraint('rank'),
    sa.UniqueConstraint('rank')
    )
    op.create_table('top_posts',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id', 'forum_id'], ['post.post_id', 'post.forum_id'], name='fk_top_posts_i'),
    sa.PrimaryKeyConstraint('rank'),
    sa.UniqueConstraint('post_id'),
    sa.UniqueConstraint('rank')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_posts')
    op.drop_table('top_forums')
    # ### end Alembic commands ###
