"""dates

Revision ID: 37a39d65afd5
Revises: fd779e9f099c
Create Date: 2019-12-05 16:17:27.325313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a39d65afd5'
down_revision = 'fd779e9f099c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('date_liked', sa.DateTime(), nullable=False))
    op.add_column('reaction', sa.Column('date_commented', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reaction', 'date_commented')
    op.drop_column('likes', 'date_liked')
    # ### end Alembic commands ###
