"""modifications to prescriptions table

Revision ID: 4f494263af8b
Revises: 6eefdd16e3ed
Create Date: 2019-12-11 20:23:00.924058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f494263af8b'
down_revision = '6eefdd16e3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Integer(), nullable=False),
    sa.Column('blood_pressure', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.alter_column('prescription', 'frequency',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('prescription', 'time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescription', 'time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('prescription', 'frequency',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_table('health_check')
    # ### end Alembic commands ###
