"""itches

Revision ID: 57d3facc3982
Revises: b813fc043ec9
Create Date: 2019-10-31 16:47:44.439806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57d3facc3982'
down_revision = 'b813fc043ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('unique_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('insurance',
    sa.Column('insurance_id', sa.Integer(), nullable=False),
    sa.Column('insurance_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('insurance_id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_default'), 'role', ['default'], unique=False)
    op.create_table('facility',
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('facility_num', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.unique_id'], ),
    sa.PrimaryKeyConstraint('hospital_id', 'facility_num')
    )
    op.create_index(op.f('ix_facility_facility_num'), 'facility', ['facility_num'], unique=False)
    op.create_index(op.f('ix_facility_hospital_id'), 'facility', ['hospital_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('nurse',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.unique_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patient',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('SSN', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('insurance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.unique_id'], ),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurance.insurance_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('physician',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.unique_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('physician_schedule',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('physician_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['physician_id'], ['physician.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('prescription',
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('physician_id', sa.Integer(), nullable=False),
    sa.Column('date_prescribed', sa.Date(), nullable=False),
    sa.Column('expir_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.user_id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physician.user_id'], ),
    sa.PrimaryKeyConstraint('prescription_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('facility_num', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['physician_schedule.event_id'], ),
    sa.ForeignKeyConstraint(['facility_num'], ['facility.facility_num'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['facility.hospital_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.user_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.drop_table('Prescription')
    op.drop_table('Room')
    op.drop_table('Hospital')
    op.drop_index('email', table_name='Physician')
    op.drop_table('Physician')
    op.drop_index('email', table_name='Patient')
    op.drop_index('ssn', table_name='Patient')
    op.drop_table('Patient')
    op.drop_table('Appointment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Appointment',
    sa.Column('appointment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=False),
    sa.Column('physician_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.id'], name='appointment_ibfk_2'),
    sa.ForeignKeyConstraint(['physician_id'], ['Physician.id'], name='appointment_ibfk_1'),
    sa.PrimaryKeyConstraint('appointment_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Patient',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('ssn', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('dob', mysql.DATETIME(), nullable=True),
    sa.Column('physician_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['physician_id'], ['Physician.id'], name='patient_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ssn', 'Patient', ['ssn'], unique=True)
    op.create_index('email', 'Patient', ['email'], unique=True)
    op.create_table('Physician',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('hospital', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hospital'], ['Hospital.id'], name='physician_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'Physician', ['email'], unique=True)
    op.create_table('Hospital',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('zipcode', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Room',
    sa.Column('room_number', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('building', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('hospital', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hospital'], ['Hospital.id'], name='room_ibfk_1'),
    sa.PrimaryKeyConstraint('room_number'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Prescription',
    sa.Column('medication', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('date_prescribed', mysql.DATETIME(), nullable=False),
    sa.Column('date_expired', mysql.DATETIME(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('physician_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.id'], name='prescription_ibfk_1'),
    sa.ForeignKeyConstraint(['physician_id'], ['Physician.id'], name='prescription_ibfk_2'),
    sa.PrimaryKeyConstraint('medication', 'date_prescribed', 'patient_id', 'physician_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('appointment')
    op.drop_table('prescription')
    op.drop_table('physician_schedule')
    op.drop_table('physician')
    op.drop_table('patient')
    op.drop_table('nurse')
    op.drop_table('user')
    op.drop_index(op.f('ix_facility_hospital_id'), table_name='facility')
    op.drop_index(op.f('ix_facility_facility_num'), table_name='facility')
    op.drop_table('facility')
    op.drop_index(op.f('ix_role_default'), table_name='role')
    op.drop_table('role')
    op.drop_table('insurance')
    op.drop_table('hospital')
    # ### end Alembic commands ###
