"""new column in prescription

Revision ID: 5e177baa30e0
Revises: 7e7a3e91e5e3
Create Date: 2019-12-11 02:55:50.864194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e177baa30e0'
down_revision = '7e7a3e91e5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription', sa.Column('last_notified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription', 'last_notified')
    # ### end Alembic commands ###
