"""procedural

Revision ID: 625dda5f8fdc
Revises: d206d49ea931
Create Date: 2019-12-11 18:27:45.538777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625dda5f8fdc'
down_revision = 'd206d49ea931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_check',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('physician_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Integer(), nullable=False),
    sa.Column('blood_pressure', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.user_id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physician.user_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.add_column('prescription', sa.Column('frequency', sa.String(length=32), nullable=False))
    op.add_column('prescription', sa.Column('last_notified', sa.DateTime(), nullable=True))
    op.add_column('prescription', sa.Column('time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription', 'time')
    op.drop_column('prescription', 'last_notified')
    op.drop_column('prescription', 'frequency')
    op.drop_table('health_check')
    # ### end Alembic commands ###
