"""latest

Revision ID: 677d405e30e1
Revises: 438311de307e
Create Date: 2019-11-10 00:26:38.652993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677d405e30e1'
down_revision = '438311de307e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'hospital', ['hospital_id'], ['unique_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'hospital_id')
    # ### end Alembic commands ###
