"""new row in top_posts

Revision ID: 6b07301ec234
Revises: 68f9555e86d3
Create Date: 2019-12-07 19:36:41.227907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b07301ec234'
down_revision = '68f9555e86d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_posts', sa.Column('forum_name', sa.String(length=128), nullable=False))
    op.create_foreign_key(None, 'top_posts', 'forum', ['forum_name'], ['forum_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'top_posts', type_='foreignkey')
    op.drop_column('top_posts', 'forum_name')
    # ### end Alembic commands ###
