"""top

Revision ID: 7ce0749575e3
Revises: 08286575be7f
Create Date: 2019-12-05 17:42:52.569623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce0749575e3'
down_revision = '08286575be7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_posts',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['post.forum_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('rank')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_posts')
    # ### end Alembic commands ###
