"""adding times and frequency

Revision ID: 7e7a3e91e5e3
Revises: d3453fd69454
Create Date: 2019-12-10 19:57:35.831885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7a3e91e5e3'
down_revision = 'd3453fd69454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription', sa.Column('frequency', sa.String(length=32), nullable=True))
    op.add_column('prescription', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prescription', 'time')
    op.drop_column('prescription', 'frequency')
    # ### end Alembic commands ###
