"""build forum

Revision ID: 8cf2a2bd824c
Revises: 5758be4d6f98
Create Date: 2019-12-05 15:18:37.804983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf2a2bd824c'
down_revision = '5758be4d6f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('forum_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('forum_id'),
    sa.UniqueConstraint('forum_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum')
    # ### end Alembic commands ###
