"""profile

Revision ID: 9d4c99dddfe8
Revises: 62d9bd101545
Create Date: 2019-12-07 20:52:54.292420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4c99dddfe8'
down_revision = '62d9bd101545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_profile', sa.Column('username', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'forum_profile', ['username'])
    op.add_column('top_posts', sa.Column('forum_name', sa.String(length=128), nullable=False))
    op.create_foreign_key(None, 'top_posts', 'forum', ['forum_name'], ['forum_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'top_posts', type_='foreignkey')
    op.drop_column('top_posts', 'forum_name')
    op.drop_constraint(None, 'forum_profile', type_='unique')
    op.drop_column('forum_profile', 'username')
    # ### end Alembic commands ###
