"""Hello

Revision ID: a65636506135
Revises: da9f37cbff97
Create Date: 2019-11-07 20:43:17.776859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a65636506135'
down_revision = 'da9f37cbff97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nurse_ibfk_2', 'nurse', type_='foreignkey')
    op.drop_column('nurse', 'hospital_id')
    op.drop_constraint('patient_ibfk_2', 'patient', type_='foreignkey')
    op.drop_column('patient', 'hospital_id')
    op.drop_constraint('physician_ibfk_2', 'physician', type_='foreignkey')
    op.drop_column('physician', 'hospital_id')
    op.add_column('user', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'hospital', ['hospital_id'], ['unique_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'hospital_id')
    op.add_column('physician', sa.Column('hospital_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('physician_ibfk_2', 'physician', 'hospital', ['hospital_id'], ['unique_id'])
    op.add_column('patient', sa.Column('hospital_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('patient_ibfk_2', 'patient', 'hospital', ['hospital_id'], ['unique_id'])
    op.add_column('nurse', sa.Column('hospital_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('nurse_ibfk_2', 'nurse', 'hospital', ['hospital_id'], ['unique_id'])
    # ### end Alembic commands ###
