"""updates to Top Posts

Revision ID: a7fdeff86371
Revises: c203896af590
Create Date: 2019-12-06 16:24:05.179476

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7fdeff86371'
down_revision = 'c203896af590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('top_posts_ibfk_3', 'top_posts', type_='foreignkey')
    op.drop_column('top_posts', 'subscribers')
    op.drop_column('top_posts', 'hospital_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_posts', sa.Column('hospital_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('top_posts', sa.Column('subscribers', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('top_posts_ibfk_3', 'top_posts', 'hospital', ['hospital_id'], ['unique_id'])
    # ### end Alembic commands ###
