"""new changes

Revision ID: a871cc1c6296
Revises: b813fc043ec9
Create Date: 2019-11-02 18:38:53.578577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a871cc1c6296'
down_revision = 'b813fc043ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('purpose', sa.String(length=64), nullable=True))
    op.alter_column('appointment', 'event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('appointment', 'facility_num',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'facility_num',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('appointment', 'event_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('appointment', 'purpose')
    # ### end Alembic commands ###
