"""procedural

Revision ID: b44bba13a044
Revises: 8604484f4a01
Create Date: 2019-12-11 22:36:01.326228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44bba13a044'
down_revision = '8604484f4a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nurse', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('physician', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('physician', 'active')
    op.drop_column('nurse', 'active')
    # ### end Alembic commands ###
