"""procedural

Revision ID: bfc4d50d84b7
Revises: 4f68b685e401
Create Date: 2019-12-11 15:21:24.551570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfc4d50d84b7'
down_revision = '4f68b685e401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription', sa.Column('frequency', sa.String(length=32), nullable=False))
    op.add_column('prescription', sa.Column('last_notified', sa.DateTime(), nullable=True))
    op.add_column('prescription', sa.Column('time', sa.Integer(), nullable=False))
    op.alter_column('prescription', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('prescription', 'notify',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prescription', 'notify',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('prescription', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.drop_column('prescription', 'time')
    op.drop_column('prescription', 'last_notified')
    op.drop_column('prescription', 'frequency')
    # ### end Alembic commands ###
