"""top_changes

Revision ID: c203896af590
Revises: f620bb8145bd
Create Date: 2019-12-06 12:16:58.998125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c203896af590'
down_revision = 'f620bb8145bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('time_requested', sa.DateTime(), nullable=True))
    op.drop_column('task', 'complete_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('complete_date', mysql.DATETIME(), nullable=True))
    op.drop_column('task', 'time_requested')
    # ### end Alembic commands ###
