"""top

Revision ID: c434d38b3bd1
Revises: 332d13c99688
Create Date: 2019-12-05 17:31:06.023383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c434d38b3bd1'
down_revision = '332d13c99688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_posts',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('forum_id', sa.Integer(), nullable=True),
    sa.Column('subscribers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id', 'forum_id'], ['post.post_id', 'post.forum_id'], name='fk_top_posts_i'),
    sa.PrimaryKeyConstraint('rank'),
    sa.UniqueConstraint('rank')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_posts')
    # ### end Alembic commands ###
