"""profile

Revision ID: caec709fd2eb
Revises: 9d4c99dddfe8
Create Date: 2019-12-07 20:53:49.505029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caec709fd2eb'
down_revision = '9d4c99dddfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key(None, 'top_posts', 'forum', ['forum_name'], ['forum_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'top_posts', type_='foreignkey')
    op.drop_table('forum_profile')
    # ### end Alembic commands ###
