"""top_changes

Revision ID: cbd6f1bda733
Revises: 077e71b650bb
Create Date: 2019-12-06 01:35:59.573152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbd6f1bda733'
down_revision = '077e71b650bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_forums', sa.Column('hospital_id', sa.Integer(), nullable=False))
    op.drop_index('rank', table_name='top_forums')
    op.create_foreign_key(None, 'top_forums', 'hospital', ['hospital_id'], ['unique_id'])
    op.drop_column('top_forums', 'rank')
    op.add_column('top_posts', sa.Column('hospital_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'top_posts', 'hospital', ['hospital_id'], ['unique_id'])
    op.drop_column('top_posts', 'rank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_posts', sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'top_posts', type_='foreignkey')
    op.drop_column('top_posts', 'hospital_id')
    op.add_column('top_forums', sa.Column('rank', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'top_forums', type_='foreignkey')
    op.create_index('rank', 'top_forums', ['rank'], unique=True)
    op.drop_column('top_forums', 'hospital_id')
    # ### end Alembic commands ###
