"""This could work? Maybe ... Not

Revision ID: d18c4c8e4dec
Revises: 
Create Date: 2019-10-23 15:00:46.736259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18c4c8e4dec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Room')
    op.drop_table('Hospital')
    op.drop_table('Physician')
    op.drop_table('Appointment')
    op.drop_table('Patient')
    op.drop_table('Prescription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prescription',
    sa.Column('medication', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date_prescribed', sa.DATETIME(), nullable=False),
    sa.Column('date_expired', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('physician_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['Physician.id'], ),
    sa.PrimaryKeyConstraint('medication', 'date_prescribed', 'patient_id', 'physician_id')
    )
    op.create_table('Patient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ssn', sa.INTEGER(), nullable=False),
    sa.Column('dob', sa.DATETIME(), nullable=True),
    sa.Column('physician_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['physician_id'], ['Physician.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ssn')
    )
    op.create_table('Appointment',
    sa.Column('appointment_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('physician_id', sa.INTEGER(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['Patient.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['Physician.id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('Physician',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('hospital', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['hospital'], ['Hospital.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Hospital',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('country', sa.VARCHAR(length=64), nullable=False),
    sa.Column('state', sa.VARCHAR(length=64), nullable=False),
    sa.Column('city', sa.VARCHAR(length=64), nullable=False),
    sa.Column('zipcode', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Room',
    sa.Column('room_number', sa.INTEGER(), nullable=False),
    sa.Column('building', sa.VARCHAR(length=64), nullable=False),
    sa.Column('hospital', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['hospital'], ['Hospital.name'], ),
    sa.PrimaryKeyConstraint('room_number')
    )
    # ### end Alembic commands ###
