"""procedural

Revision ID: ddccdeffd43d
Revises: 2e7857e06b97
Create Date: 2019-12-11 18:47:54.541809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddccdeffd43d'
down_revision = '2e7857e06b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('health_check_ibfk_2', 'health_check', type_='foreignkey')
    op.drop_column('health_check', 'physician_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_check', sa.Column('physician_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('health_check_ibfk_2', 'health_check', 'physician', ['physician_id'], ['user_id'])
    # ### end Alembic commands ###
