"""fixing active

Revision ID: e5bd35979fbd
Revises: b44bba13a044
Create Date: 2019-12-12 05:42:51.979090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5bd35979fbd'
down_revision = 'b44bba13a044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nurse', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('physician', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('physician', 'active')
    op.drop_column('nurse', 'active')
    # ### end Alembic commands ###
