"""profile

Revision ID: ef80c6169104
Revises: caec709fd2eb
Create Date: 2019-12-07 20:54:27.896382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef80c6169104'
down_revision = 'caec709fd2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('forum_id', sa.Integer(), nullable=False),
    sa.Column('forum_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['forum_id'], ['post.forum_id'], ),
    sa.ForeignKeyConstraint(['forum_name'], ['forum.forum_name'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('post_id', 'forum_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_posts')
    # ### end Alembic commands ###
