"""hospital_id

Revision ID: fd779e9f099c
Revises: 19b00804180f
Create Date: 2019-12-05 15:59:41.587254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd779e9f099c'
down_revision = '19b00804180f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum', sa.Column('hospital_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forum', 'hospital', ['hospital_id'], ['unique_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forum', type_='foreignkey')
    op.drop_column('forum', 'hospital_id')
    # ### end Alembic commands ###
